language: python
sudo: required
dist: trusty

branch:
    only:
        - master
        - travis

install:
    # python
    - pip install -r requirements.txt
    # Install TeXLive
    ## make TexLive installation quiet
    - sudo bash install-tl.sh
    - source ~/.bash_profile
    - export TLMGR=`which tlmgr`
    # update texlive
    - sudo $TLMGR update --self --all -repository http://ctan.sharelatex.com/tex-archive/systems/texlive/tlnet/

script:
    - make linkcheck
    - make html
    - make latexpdf
    - make pre-deploy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN}
  local_dir: build/html
  on:
    branch: master
